linter:
  rules:
  # Error
  - always_specify_types
  - avoid_empty_else
  - cancel_subscriptions
  - close_sinks
  - control_flow_in_finally
  - empty_statements
  - hash_and_equals
  - test_types_in_equals
  - throw_in_finally
  - unnecessary_statements
  - unrelated_type_equality_checks
  - valid_regexps
  # Style
  - avoid_init_to_null
  - avoid_return_types_on_setters
  - await_only_futures
  - camel_case_types
  - empty_constructor_bodies
  - implementation_imports
  - library_names
  - non_constant_identifier_names
  - package_api_docs
  - package_prefixed_library_names
  - prefer_is_not_empty
  - slash_for_doc_comments
  - type_init_formals
  - unnecessary_brace_in_string_interps
  - unnecessary_getters_setters
  # Pub
  - package_names